baseurl = "https://wethod.github.io/"
canonifyurls = true
googleAnalytics = ""
languageCode = "en-us"
metadataformat = "yaml"
theme = "hugo-material-docs"
title = "WETHOD / Learning Center"
[blackfriday]
fractions = true
plainIDAnchors = true
smartDashes = true
smartypants = true
[[menu.main]]
name = "Settings"
url = "settings/index/"
weight = 80
[[menu.main]]
name = "Finance"
url = "finance/index/"
weight = 70
[[menu.main]]
name = "Reports"
url = "reports/index/"
weight = 60
[[menu.main]]
name = "Friday"
url = "friday/index/"
weight = 50
[[menu.main]]
name = "Planning"
url = "planning/index/"
weight = 40
[[menu.main]]
name = "Pipeline"
url = "pipeline/index/"
weight = 30
[[menu.main]]
name = "Dashboard"
url = "dashboard/index/"
weight = 20
[[menu.main]]
name = "Getting started"
url = "getting-started/index/"
weight = 10
[[menu.other]]
name = "FAQ"
url = "faq/index/"
weight = 100
[[menu.other]]
name = "Glossary"
url = "glossary/index/"
weight = 110
[params]
author = "Andrea Tombolato"
copyright = ""
custom_css = ["stylesheets/custom-style.css"]
custom_js = []
description = "A lean multi-project management platform that fosters the autonomy and ownership of every team member at any level."
favicon = "images/favicon.ico"
highlight_css = ""
logo = "images/logo.png"
permalink = "#"
provider = ""
repo_url = ""
version = ""
[params.font]
code = "Ubuntu Mono"
text = "Ubuntu"
[params.palette]
accent = "teal"
primary = "black"
[social]
email = "info@wethod.com"
github = ""
twitter = ""
